server:
  port: 8084


spring:
  application:
    name: person-service
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres
    #    ${SPRING_R2DBC_URL} = r2dbc:pool:postgres://localhost:5432/paymentprovider
    username: postgres
    password: postgres
    pool:
      max-validation-time: 30s
      max-size: 50
      validation-query: SELECT 1
  flyway:
    #    url: ${SPRING_FLYWAY_URL}
    url: jdbc:postgresql://localhost:5432/postgres?user=postgres&password=postgres
    locations: classpath:db/migration